### ISSUE TITLE
Trending NFTs > Popular Collections

### ISSUE THREAD

**Issue by jhobsz** [SecretChainGirl-Foundation/stashh-nft-marketplace#139] opened 2021-11-12 04:28 UTC
Clicking on any of them gives a white screen, wallet address in the address bar

**Comment by jhobsz** [comment] 2021-11-12 04:29
I clicked on Distored reality collection. 
Then I clicked on Deserts collection - actually got something back

**Comment by scarylooking** [comment] 2021-11-13 15:48
Dupe of #131

**Closed by scarylooking** 2021-11-13 15:48 UTC
