### ISSUE TITLE
Clicking on profile social media...

### ISSUE THREAD

**Issue by joelmce** [SecretChainGirl-Foundation/stashh-nft-marketplace#67] opened 2021-10-18 02:26 UTC
While clicking on peoples social media, i.e this [weird test account](https://devops-deploy.azurewebsites.net/profile/secret1gj5akeu2rvwqzcx5qg8knq8mekarzjvq228hn7):

Instead of copying it to clipboard, why not instantly direct them? 

![image](https://user-images.githubusercontent.com/15964085/137659984-624ffe6f-bc84-4e97-b866-5eaf0abeae6b.png)

Also take note of the grammatical errors. Should be capital T and lowercase C.

**Comment by scarylooking** [comment] 2021-10-19 19:29
Dupe of #41

**Closed by scarylooking** 2021-10-19 19:29 UTC
Labels: duplicate
