### ISSUE TITLE
Enhancement on NFTs/collections with no icons

### ISSUE THREAD

**Issue by pivxftw** [SecretChainGirl-Foundation/stashh-nft-marketplace#98] opened 2021-10-22 05:03 UTC
Tested in (Chrome, Safari, Edge, Firefox, etc.): Chrome

## Steps to reproduce
1. Go to 'Homepage' or Marketplace
2. In Trending NFTs or Popular Collections.

## Issue:
My immediate instinct seeing the video or picture icons is that the browser blocked the image or the image wasn't loading properly.  And I see that all over the place

## Expected:
I'm not sure how to fix this, but encourage more people upload icons and banners.  For the NFTs with no icons, perhaps use the stashh diamond icon instead?

**Comment by joelmce** [comment] 2021-10-23 00:50
Dupe of #91?

**Comment by scarylooking** [comment] 2021-11-08 22:46
Closing this as a dupe

**Closed by scarylooking** 2021-11-08 22:46 UTC
Labels: duplicate
